# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee1e9eb6ea98801289aee1762dc68463bf3855f5000ae2473c0e05ecb5005c05ec02f43d25d8d53720e089188654bd5d05507383047fdca75ad1e3104a852a20

test:
  secret_key_base: 2f01f4f126426d73156e0f8011b44ef14b980cb740a85a9cd3c0486ac99e91866767be6e94350157e0dded1c144973517a9636a0bb053e844c82ca5981dc96a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
